version: "{build}"

image: Visual Studio 2017

# Troubleshooting
# on_finish:
#   - ps: $blockRdp = $true; iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-rdp.ps1'))

branches:
  only:
  - master
  - develop

configuration:
- Release

before_build:
  - mkdir build
  - cd vcproj
  - cmake .. -G "Visual Studio 15 2017"
  - cd ..
  - cd vcproj64
  - cmake .. -G "Visual Studio 15 2017 Win64" "-DUSE_64BIT_BUILD=ON"
  - cd ..

build:
  parallel: true
  verbosity: minimal

build_script:
  - msbuild vcproj\Intercept.sln /m
  - msbuild vcproj64\Intercept.sln /m 
  
on_success:
  - ps: .\tools\ci_publish_artifacts.ps1

artifacts:
- path: build\win32\intercept_client\Release\intercept_client.lib
  name: win32_client_lib
- path: build\win32\intercept\Release\intercept.dll
  name: win32_host_lib
- path: build\win32\intercept\Release\intercept.pdb
  name: win32_host_pdb
- path: build\win64\intercept_client\Release\intercept_client.lib
  name: win64_client_lib
- path: build\win64\intercept\Release\intercept_x64.dll
  name: win64_host_lib
- path: build\win64\intercept\Release\intercept_x64.pdb
  name: win32_host_pdb
